apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ml
  namespace: leadscore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-ml
  template:
    metadata:
      labels:
        app: fastapi-ml
    spec:
      containers:
        - name: api
          image: fastapi-ml-skeleton:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: fastapi-ml-secret
                  key: API_KEY
            - name: DEFAULT_MODEL_PATH
              value: "/app/sample_model/lin_reg_california_housing_model.joblib"
          readinessProbe:
            httpGet:
              path: /api/health/heartbeat
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health/heartbeat
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
