apiVersion: v1
kind: Service
metadata:
  name: fastapi-ml-svc
  namespace: leadscore
spec:
  selector:
    app: fastapi-ml
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
