replicaCount: 2

image:
  repository: fastapi-ml-skeleton
  tag: local
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

secret:
  name: fastapi-ml-secret
  key: API_KEY

probes:
  path: /api/health/heartbeat
  readinessInitialDelaySeconds: 5
  readinessPeriodSeconds: 5
  livenessInitialDelaySeconds: 15
  livenessPeriodSeconds: 10

env:
  DEFAULT_MODEL_PATH: "/app/sample_model/lin_reg_california_housing_model.joblib"

resources:
  requests:
    memory: "128Mi"     # min memory
    cpu: "100m"         # min CPU (0.1 core)
  limits:
    memory: "512Mi"     # max memory
    cpu: "500m"         # max CPU (0.5 core)

# Prometheus/Grafana
monitoring:
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "1000m"